config/routes.rb
Rails.application.routes.draw do

  get '/profile/show' => "profiles#show", as: :profile
  get '/profile/edit' => "profiles#edit", as: :profile_edit
  patch '/profile/edit' => "profiles#update"
  
  root 'home#index'

  resources :users

  get '/register' => "users#register"

  # Session maagement
  get  "/login"  => "sessions#new"
  post "/login"  => "sessions#create"
  get  "/logout" => "sessions#destroy", as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    validates_confirmation_of :password

    # We need to add a method to the user object for authentication
    def self.authenticate(email, password)

        # First check the email, if exists
        user = User.where(email: email).first

        # Now we grab the salt of the user, and encrypt the password
        # if the new hash matches the one in the DB, the login is successful
        if user && user.pass_hash == BCrypt::Engine.hash_secret(password, user.pass_salt)
            user
        else
            nil
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Establish an "current_user" object in the session to handle the user information
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # Method that locks controllers actions, if a user is not logged, then should 
  # redirect to the login view
  def authorize
    redirect_to '/login' unless current_user
  end

  # Method that locks controllers actions, so we can define special admin actions
  # TODO: Add notice and a proper redirect
  def admin_user
    if current_user.usertype != 0
      redirect_to '/login'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
  end

  def edit
  end


  # PATCH/PUT /users/1
  def update

      # First receive the user params
      updateparms = user_params

      # Now we add a pass_hash to the params with the new password
      if !updateparms[:password].empty?
        updateparms[:pass_hash] = BCrypt::Engine.hash_secret(updateparms[:password], @profile.pass_salt)
      end

      # The update method will do the rest of the work
      if @profile.update(updateparms)
        redirect_to profile_path, notice: 'Data successfully updated.'
      else
        render :edit
      end

    end

  private
  def set_user
    @profile = User.find(current_user.id)
  end
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # Login Page
  def new
    if current_user
      redirect_to root_path
    end
  end
  
  # Create a new session using the authenticate from our model
  def create

    # Check the user existence and password
    user =  User.authenticate(params[:email], params[:password])
    
    if user
       # IF everyting is okay, redirect to root
      session[:user_id] = user.id
      redirect_to root_path
    else 
      # IF the login fails, return to login page with error message
      flash[:notice] = "Login failed"
      redirect_to login_path
    end

  end

  # Close the session 
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to root_path
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:register]
  before_action :admin_user, except: [:register]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/new
  def register
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create

    # Create a new user
    @user = User.new(user_params)

    # Encrypt the password
    @user.pass_salt = BCrypt::Engine.generate_salt
    @user.pass_hash = BCrypt::Engine.hash_secret(@user.password, @user.pass_salt)

    # Each user has a unique salt
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
      render :show, status: :created, location: @user
    else
      render :new 
    end

  end

  # PATCH/PUT /users/1
  def update

      # First receive the user params
      updateparms = user_params

      # Now we add a pass_hash to the params with the new password
      updateparms[:pass_hash] = BCrypt::Engine.hash_secret(updateparms[:password], @user.pass_salt)

      # The update method will do the rest of the work
      if @user.update(updateparms)
        redirect_to @user, notice: 'User was successfully updated.'
        render :show, status: :ok, location: @user
      else
        render :edit
      end

    end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :usertype, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h2>User profiles</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Profiles</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bgmain">
    
    <div class="container">

      <%= render 'shared/nav' %>

      <p id="notice"><%= notice %></p>

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <%= yield %>
        </div> 
        <div class="col-md-2"></div>
      </div>

    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: profile_edit_path, smethod: :put  do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    Change password (leave empty to keep the same)<br>
    <%= form.password_field :password, placeholder: 'Password'%>
    <%= form.password_field :password_confirmation, placeholder: 'Confirm Password'%>
  </div>

  <div class="field">
  <%= case @profile.usertype
    when 1 
      'Hunter'
    when 2
      'Seeker'
    when 0
       'Admin'
    end  
  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Information</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Profile</h1>
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Account Type:</strong>
  <%= case @profile.usertype
    when 1 
      'Hunter'
    when 2
      'Seeker'
    when 0
       'Admin'
    end  
  %>
</p>

<%=link_to 'Edit Profile', profile_edit_path%>

app/views/shared/_nav.html.erb
<%=link_to "Home", root_path %> | 

<% if current_user %>
    <%=link_to current_user.email, profile_path %>
    | <%=link_to "Logout", logout_path %>
<% else %>
    <%= link_to "Register", register_path %>
    | <%=link_to "Login", login_path %>
<% end %>

<% if current_user && current_user.usertype == 0 %>
    | <%=link_to "Admin", users_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  

  <div class="field">
    <%= @user.persisted? ? 'Change password' : 'Password' %><br>
    <%= form.password_field :password, placeholder: 'Password'%>
    <%= form.password_field :password_confirmation, placeholder: 'Confirm Password'%>
  </div>

  <div class="field">
    <%= form.label :usertype %>
    <%= form.select :usertype, options_for_select([["Admin", 0],["Hunter", 1], ["Seeker", 2]]) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= case user.usertype
            when 1 
              'Hunter'
            when 2
              'Seeker'
            when 0
              'Admin'
            end  
          %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/register.html.erb
<h1>Register User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= case @user.usertype
     when 1 
      'Hunter'
    when 2
      'Seeker'
    when 0
       'Admin'
    end  
  %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>